using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SealAnalyzer;

[Generator]
public sealed class SealPublicClassesGenerator : IIncrementalGenerator
{
	public const string Namespace = "AutoSeal";
	public const string AttributeName = "SealPublicClassesAttribute";

	private const string Source = $$"""
	                                //------------------------------------------------------------------------------
	                                // <auto-generated>
	                                //     This code was generated by a tool {{ThisAssembly.Info.Title}}.
	                                //     Runtime Version: {{ThisAssembly.Info.Version}}
	                                //
	                                //     Changes to this file may cause incorrect behavior and will be lost if
	                                //     the code is regenerated.
	                                // </auto-generated>
	                                //------------------------------------------------------------------------------
	                                #nullable enable

	                                namespace {{Namespace}}
	                                {

	                                    /// <summary>
	                                    /// Makes the seal analyzer work on `public` classes.
	                                    /// </summary>
	                                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	                                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	                                    [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
	                                    [global::System.CodeDom.Compiler.GeneratedCode("{{ThisAssembly.Info.Title}}", "{{ThisAssembly.Info.Version}}")]
	                                    [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = false)]
	                                    internal sealed class {{AttributeName}} : global::System.Attribute 
	                                    {
	                                    }
	                                }
	                                #nullable restore
	                                """;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// We simply add the source code for the attribute to the compilation
		context.RegisterPostInitializationOutput(ctx => {
			ctx.AddEmbeddedAttributeDefinition();
			ctx.AddSource("SealPublicClassesAttribute.g.cs", SourceText.From(Source, Encoding.UTF8));
		});
	}
}